export enum OnboardingStatus {
    STARTED = 'STARTED',
    AWAITING_AUDIO = 'AWAITING_AUDIO',
    AUDIO_UPLOADED = 'AUDIO_UPLOADED',
    PROCESSING = 'PROCESSING',
    NEEDS_CLARIFICATION = 'NEEDS_CLARIFICATION',
    READY_FOR_REVIEW = 'READY_FOR_REVIEW',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    EXPIRED = 'EXPIRED',
} 